package review

import (
	"strings"
	"testing"
	"time"

	"github.com/dgrieser/nickpit/internal/git"
	"github.com/dgrieser/nickpit/internal/model"
)

type exactEstimator struct{}

func (exactEstimator) Estimate(text string) int {
	return len(text)
}

func (exactEstimator) EstimateLen(length int) int {
	return length
}

func TestTrimmerDropsGeneratedFlaggedFiles(t *testing.T) {
	trimmer := NewTrimmer(1, model.SimpleEstimator{})
	ctx, err := trimmer.Trim(&model.ReviewContext{
		Title: strings.Repeat("x", 100),
		ChangedFiles: []model.ChangedFile{
			{Path: "pkg/service.go", Status: model.FileModified},
			{Path: "pkg/service.pb.go", Status: model.FileModified, Generated: true},
			{Path: "web/package-lock.json", Status: model.FileModified, Generated: true},
		},
		Diff: "diff --git a/pkg/service.go b/pkg/service.go\n@@ -1 +1 @@\n-old\n+new\n" +
			"diff --git a/pkg/service.pb.go b/pkg/service.pb.go\n@@ -1 +1 @@\n-old\n+new\n" +
			"diff --git a/web/package-lock.json b/web/package-lock.json\n@@ -1 +1 @@\n-old\n+new\n",
		DiffFiles: []model.DiffFile{
			{FilePath: "pkg/service.go", Content: "diff --git a/pkg/service.go b/pkg/service.go\n@@ -1 +1 @@\n-old\n+new\n"},
			{FilePath: "pkg/service.pb.go", Content: "diff --git a/pkg/service.pb.go b/pkg/service.pb.go\n@@ -1 +1 @@\n-old\n+new\n", Generated: true},
			{FilePath: "web/package-lock.json", Content: "diff --git a/web/package-lock.json b/web/package-lock.json\n@@ -1 +1 @@\n-old\n+new\n", Generated: true},
		},
		DiffHunks: []model.DiffHunk{
			{FilePath: "pkg/service.go", Content: "-old\n+new\n"},
			{FilePath: "pkg/service.pb.go", Content: "-old\n+new\n"},
			{FilePath: "web/package-lock.json", Content: "-old\n+new\n"},
		},
		SupplementalContext: []model.SupplementalFile{
			{Path: "pkg/service.pb.go", Content: "package pkg\n", Kind: "full_file"},
		},
	})
	if err != nil {
		t.Fatalf("Trim: %v", err)
	}

	if len(ctx.ChangedFiles) != 1 || ctx.ChangedFiles[0].Path != "pkg/service.go" {
		t.Fatalf("changed files = %#v", ctx.ChangedFiles)
	}
	if len(ctx.DiffFiles) != 1 || ctx.DiffFiles[0].FilePath != "pkg/service.go" {
		t.Fatalf("diff files = %#v", ctx.DiffFiles)
	}
	if len(ctx.DiffHunks) != 1 || ctx.DiffHunks[0].FilePath != "pkg/service.go" {
		t.Fatalf("diff hunks = %#v", ctx.DiffHunks)
	}
	if strings.Contains(ctx.Diff, "service.pb.go") || strings.Contains(ctx.Diff, "package-lock.json") {
		t.Fatalf("diff still includes generated paths: %q", ctx.Diff)
	}
	if len(ctx.SupplementalContext) != 0 {
		t.Fatalf("supplemental full file for generated path survived: %#v", ctx.SupplementalContext)
	}
	if len(ctx.OmittedSections) == 0 || !strings.Contains(ctx.OmittedSections[0], "generated files omitted") {
		t.Fatalf("omitted sections = %#v", ctx.OmittedSections)
	}
}

func TestStampGeneratedFlagsFromEmbeddedMappings(t *testing.T) {
	diff := strings.Join([]string{
		"diff --git a/pkg/service.pb.go b/pkg/service.pb.go",
		"@@ -1 +1 @@",
		"-old",
		"+new",
		"diff --git a/Cargo.lock b/Cargo.lock",
		"@@ -1 +1 @@",
		"-old",
		"+new",
		"diff --git a/gen/models.go b/gen/models.go",
		"@@ -1,2 +1,2 @@",
		"-// Code generated by mockgen. DO NOT EDIT.",
		"+// Code generated by mockgen v2. DO NOT EDIT.",
		"diff --git a/pkg/service.go b/pkg/service.go",
		"@@ -1 +1 @@",
		"-old",
		"+new",
		"",
	}, "\n")
	diffFiles, hunks, changed, err := git.ParseUnifiedDiffFormats(diff)
	if err != nil {
		t.Fatal(err)
	}
	reviewCtx := &model.ReviewContext{
		ChangedFiles: changed,
		Diff:         diff,
		DiffFiles:    diffFiles,
		DiffHunks:    hunks,
	}
	stampGeneratedFlags(reviewCtx)

	trimmed, err := NewTrimmer(1, model.SimpleEstimator{}).Trim(reviewCtx)
	if err != nil {
		t.Fatalf("Trim: %v", err)
	}
	if len(trimmed.ChangedFiles) != 1 || trimmed.ChangedFiles[0].Path != "pkg/service.go" {
		t.Fatalf("changed files = %#v", trimmed.ChangedFiles)
	}
	for _, path := range []string{"service.pb.go", "Cargo.lock", "gen/models.go"} {
		if strings.Contains(trimmed.Diff, path) {
			t.Fatalf("diff still includes generated path %s: %q", path, trimmed.Diff)
		}
	}
	if len(trimmed.OmittedSections) == 0 || !strings.Contains(trimmed.OmittedSections[0], "generated files omitted") {
		t.Fatalf("omitted sections = %#v", trimmed.OmittedSections)
	}
}

func TestTrimmerEvictionTieBreakIsDeterministic(t *testing.T) {
	for range 5 {
		diffFiles := []model.DiffFile{
			testDiffFile("b.go", 40),
			testDiffFile("a.go", 40),
		}
		ctx := &model.ReviewContext{
			DiffFiles: diffFiles,
		}
		trimmer := NewTrimmer(len(diffFiles[0].Content)+1, exactEstimator{})
		trimmed, err := trimmer.Trim(ctx)
		if err != nil {
			t.Fatalf("Trim: %v", err)
		}
		if len(trimmed.DiffFiles) != 1 || trimmed.DiffFiles[0].FilePath != "b.go" {
			t.Fatalf("diff files = %#v, want deterministic eviction of a.go", trimmed.DiffFiles)
		}
	}
}

func TestTrimmerEvictsLowerPriorityClassesFirst(t *testing.T) {
	diffFiles := []model.DiffFile{
		testDiffFile("pkg/main.go", 100),
		testDiffFile("README.md", 30),
		testDiffFile("pkg/main_test.go", 60),
	}
	ctx := &model.ReviewContext{DiffFiles: diffFiles}
	// Budget forces two evictions: docs first, tests second, source survives.
	trimmer := NewTrimmer(len(diffFiles[0].Content)+1, exactEstimator{})
	trimmed, err := trimmer.Trim(ctx)
	if err != nil {
		t.Fatalf("Trim: %v", err)
	}
	if len(trimmed.DiffFiles) != 1 || trimmed.DiffFiles[0].FilePath != "pkg/main.go" {
		t.Fatalf("diff files = %#v, want docs and tests evicted before source", trimmed.DiffFiles)
	}
	if len(trimmed.OmittedSections) == 0 || !strings.Contains(trimmed.OmittedSections[0], "diff files omitted to fit context budget") {
		t.Fatalf("omitted sections = %#v", trimmed.OmittedSections)
	}
	if !strings.Contains(trimmed.OmittedSections[0], "README.md (") || !strings.Contains(trimmed.OmittedSections[0], "bytes)") {
		t.Fatalf("omission entry missing name and size: %#v", trimmed.OmittedSections)
	}
}

func TestTrimmerRecordsOmissionsPerStage(t *testing.T) {
	now := time.Now()
	ctx := &model.ReviewContext{
		Comments: []model.Comment{
			{Body: strings.Repeat("c", 50), CreatedAt: now.Add(-time.Hour)},
			{Body: strings.Repeat("d", 50), CreatedAt: now},
		},
		Commits: []model.CommitSummary{
			{Message: "subject one\n\nbody one"},
			{Message: "subject two\n\nbody two"},
		},
		SupplementalContext: []model.SupplementalFile{
			{Path: "pkg/service.go", Content: strings.Repeat("s", 80), Kind: "full_file"},
		},
		DiffFiles: []model.DiffFile{
			testDiffFile("a.go", 40),
			testDiffFile("b.go", 60),
		},
	}
	trimmer := NewTrimmer(len(testDiffFile("a.go", 40).Content)+len("subject one")+len("subject two")+1, exactEstimator{})
	trimmed, err := trimmer.Trim(ctx)
	if err != nil {
		t.Fatalf("Trim: %v", err)
	}
	joined := strings.Join(trimmed.OmittedSections, "\n")
	for _, want := range []string{
		"older comments omitted",
		"supplemental context omitted: pkg/service.go",
		"commit message bodies omitted (subjects kept)",
		"diff files omitted to fit context budget: b.go (",
	} {
		if !strings.Contains(joined, want) {
			t.Fatalf("omitted sections missing %q: %#v", want, trimmed.OmittedSections)
		}
	}
}

func TestTrimmerDropsSupplementalBeforeFlatteningCommits(t *testing.T) {
	ctx := &model.ReviewContext{
		Commits: []model.CommitSummary{
			{Message: "subject\n\nimportant body"},
		},
		SupplementalContext: []model.SupplementalFile{
			{Path: "pkg/service.go", Content: strings.Repeat("s", 100), Kind: "full_file"},
		},
	}
	trimmer := NewTrimmer(len("subject\n\nimportant body")+1, exactEstimator{})
	trimmed, err := trimmer.Trim(ctx)
	if err != nil {
		t.Fatalf("Trim: %v", err)
	}
	if len(trimmed.SupplementalContext) != 0 {
		t.Fatalf("supplemental context survived: %#v", trimmed.SupplementalContext)
	}
	if trimmed.Commits[0].Message != "subject\n\nimportant body" {
		t.Fatalf("commit body flattened although dropping supplemental sufficed: %q", trimmed.Commits[0].Message)
	}
}

func TestTrimmerHeadroomReducesBudget(t *testing.T) {
	build := func() *model.ReviewContext {
		return &model.ReviewContext{
			DiffFiles: []model.DiffFile{
				testDiffFile("a.go", 20),
				testDiffFile("b.go", 20),
			},
		}
	}
	total := len(testDiffFile("a.go", 20).Content) * 2

	without, err := NewTrimmer(total, exactEstimator{}).Trim(build())
	if err != nil {
		t.Fatalf("Trim: %v", err)
	}
	if len(without.DiffFiles) != 2 {
		t.Fatalf("without headroom diff files = %#v, want untouched", without.DiffFiles)
	}

	with, err := NewTrimmer(total, exactEstimator{}, WithHeadroomTokens(total/2)).Trim(build())
	if err != nil {
		t.Fatalf("Trim: %v", err)
	}
	if len(with.DiffFiles) != 1 {
		t.Fatalf("with headroom diff files = %#v, want one file evicted", with.DiffFiles)
	}
}

func TestTrimmerResultFitsBudgetWithSimpleEstimator(t *testing.T) {
	ctx := &model.ReviewContext{
		Title: strings.Repeat("t", 200),
		DiffFiles: []model.DiffFile{
			testDiffFile("a.go", 400),
			testDiffFile("b.go", 300),
			testDiffFile("c.go", 500),
		},
		Comments: []model.Comment{
			{Body: strings.Repeat("c", 400)},
			{Body: strings.Repeat("d", 400)},
		},
	}
	maxTokens := 300
	trimmer := NewTrimmer(maxTokens, model.SimpleEstimator{})
	trimmed, err := trimmer.Trim(ctx)
	if err != nil {
		t.Fatalf("Trim: %v", err)
	}
	if got := (model.SimpleEstimator{}).Estimate(renderContextText(trimmed)); got > maxTokens {
		t.Fatalf("trimmed context estimates %d tokens, budget %d", got, maxTokens)
	}
}

func TestTrimmerDiffFilesPruningUsesPrunedFormat(t *testing.T) {
	diffFiles := []model.DiffFile{
		testDiffFile("a.go", 40),
		testDiffFile("b.go", 40),
		testDiffFile("c.go", 80),
	}
	ctx := &model.ReviewContext{
		Diff:      diffFileContent(diffFiles),
		DiffFiles: diffFiles,
		DiffHunks: []model.DiffHunk{
			{FilePath: "a.go", Content: strings.Repeat("a", 40)},
			{FilePath: "b.go", Content: strings.Repeat("b", 40)},
			{FilePath: "c.go", Content: strings.Repeat("c", 80)},
		},
	}
	trimmer := NewTrimmer(len(diffFiles[0].Content)+len(diffFiles[1].Content)+1, exactEstimator{})

	trimmed, err := trimmer.Trim(ctx)
	if err != nil {
		t.Fatalf("Trim: %v", err)
	}

	if len(trimmed.DiffFiles) != 2 {
		t.Fatalf("diff files = %#v, want two files after pruning one oversized file", trimmed.DiffFiles)
	}
	if containsDiffFile(trimmed.DiffFiles, "c.go") {
		t.Fatalf("largest diff file was not pruned: %#v", trimmed.DiffFiles)
	}
	if len(trimmed.DiffHunks) != 2 || containsDiffHunk(trimmed.DiffHunks, "c.go") {
		t.Fatalf("diff hunks not kept in sync: %#v", trimmed.DiffHunks)
	}
	if strings.Contains(trimmed.Diff, "c.go") {
		t.Fatalf("rebuilt diff still contains pruned file: %q", trimmed.Diff)
	}
}

func TestTrimmerDiffHunksPruningUsesPrunedFormat(t *testing.T) {
	hunks := []model.DiffHunk{
		{FilePath: "a.go", Content: strings.Repeat("a", 40)},
		{FilePath: "b.go", Content: strings.Repeat("b", 40)},
		{FilePath: "c.go", Content: strings.Repeat("c", 80)},
	}
	ctx := &model.ReviewContext{
		Diff:      strings.Repeat("x", 300),
		DiffHunks: hunks,
	}
	trimmer := NewTrimmer(len(hunks[0].Content)+len(hunks[1].Content)+1, exactEstimator{})

	trimmed, err := trimmer.Trim(ctx)
	if err != nil {
		t.Fatalf("Trim: %v", err)
	}

	if len(trimmed.DiffHunks) != 2 {
		t.Fatalf("diff hunks = %#v, want two hunks after pruning one oversized hunk", trimmed.DiffHunks)
	}
	if containsDiffHunk(trimmed.DiffHunks, "c.go") {
		t.Fatalf("largest hunk was not pruned: %#v", trimmed.DiffHunks)
	}
	if strings.Contains(trimmed.Diff, "c.go") {
		t.Fatalf("rebuilt diff still contains pruned hunk: %q", trimmed.Diff)
	}
}

func testDiffFile(path string, size int) model.DiffFile {
	content := "diff --git a/" + path + " b/" + path + "\n" +
		"@@ -1 +1 @@\n" +
		"-" + strings.Repeat("o", size) + "\n" +
		"+" + strings.Repeat("n", size) + "\n"
	return model.DiffFile{FilePath: path, Language: "go", Content: content}
}

func diffFileContent(files []model.DiffFile) string {
	var out strings.Builder
	for _, file := range files {
		out.WriteString(file.Content)
	}
	return out.String()
}

func containsDiffFile(files []model.DiffFile, path string) bool {
	for _, file := range files {
		if file.FilePath == path {
			return true
		}
	}
	return false
}

func containsDiffHunk(hunks []model.DiffHunk, path string) bool {
	for _, hunk := range hunks {
		if hunk.FilePath == path {
			return true
		}
	}
	return false
}
