package git

import (
	"strings"
	"testing"
)

func TestParseDiffGitPath(t *testing.T) {
	tests := []struct {
		name string
		line string
		want string
	}{
		{
			name: "plain",
			line: "diff --git a/main.go b/main.go",
			want: "main.go",
		},
		{
			name: "space in name unquoted",
			line: "diff --git a/dir/my file.go b/dir/my file.go",
			want: "dir/my file.go",
		},
		{
			name: "space in name quoted both sides",
			line: `diff --git "a/dir/my file.go" "b/dir/my file.go"`,
			want: "dir/my file.go",
		},
		{
			name: "umlaut octal escapes",
			line: `diff --git "a/sch\303\266n.txt" "b/sch\303\266n.txt"`,
			want: "schön.txt",
		},
		{
			name: "quotes in name both sides",
			line: `diff --git "a/say \"hi\".txt" "b/say \"hi\".txt"`,
			want: `say "hi".txt`,
		},
		{
			name: "doubled backslash",
			line: `diff --git "a/back\\slash.txt" "b/back\\slash.txt"`,
			want: `back\slash.txt`,
		},
		{
			name: "tab escape",
			line: `diff --git "a/ta\tb.txt" "b/ta\tb.txt"`,
			want: "ta\tb.txt",
		},
		{
			name: "mixed quoted a unquoted b",
			line: `diff --git "a/sch\303\266n.txt" b/plain.txt`,
			want: "plain.txt",
		},
		{
			name: "mixed unquoted a quoted b",
			line: `diff --git a/plain.txt "b/sch\303\266n.txt"`,
			want: "schön.txt",
		},
		{
			name: "unquoted rename",
			line: "diff --git a/old.go b/new.go",
			want: "new.go",
		},
		{
			name: "not a diff line",
			line: "index 1234567..89abcde 100644",
			want: "",
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := parseDiffGitPath(tc.line); got != tc.want {
				t.Fatalf("parseDiffGitPath(%q) = %q, want %q", tc.line, got, tc.want)
			}
		})
	}
}

func TestParseUnifiedDiffFormatsClassifiesWithContent(t *testing.T) {
	diff := strings.Join([]string{
		"diff --git a/bin/deploy b/bin/deploy",
		"new file mode 100755",
		"@@ -0,0 +1,2 @@",
		"+#!/usr/bin/env python",
		"+import sys",
		"diff --git a/api/service.pb.go b/api/service.pb.go",
		"@@ -1,2 +1,2 @@",
		"-// Code generated by protoc-gen-go. DO NOT EDIT.",
		"+// Code generated by protoc-gen-go v2. DO NOT EDIT.",
		"",
	}, "\n")

	diffFiles, hunks, _, err := ParseUnifiedDiffFormats(diff)
	if err != nil {
		t.Fatal(err)
	}
	if len(diffFiles) != 2 {
		t.Fatalf("diff files = %d, want 2", len(diffFiles))
	}
	if diffFiles[0].Language != "python" {
		t.Fatalf("bin/deploy language = %q, want python", diffFiles[0].Language)
	}
	if diffFiles[0].Generated {
		t.Fatal("bin/deploy marked generated")
	}
	if !diffFiles[1].Generated {
		t.Fatal("api/service.pb.go not marked generated")
	}
	if len(hunks) != 2 || hunks[0].Language != "python" {
		t.Fatalf("hunk language = %+v, want python for bin/deploy", hunks)
	}
}

// A combined-diff ("@@@") hunk from a merge state must not be swallowed as
// content of the preceding file's hunk; its lines are skipped instead.
func TestParseUnifiedDiffFormatsSkipsCombinedDiffHunks(t *testing.T) {
	// Combined diffs appear with either marker: "diff --cc" (git diff during a
	// merge) and "diff --combined" (git diff-tree -c and friends). Both must
	// act as a file boundary.
	for _, marker := range []string{"diff --cc", "diff --combined"} {
		t.Run(strings.TrimPrefix(marker, "diff --"), func(t *testing.T) {
			diff := strings.Join([]string{
				"diff --git a/normal.go b/normal.go",
				"index 1111111..2222222 100644",
				"--- a/normal.go",
				"+++ b/normal.go",
				"@@ -1,2 +1,3 @@",
				" keep",
				"+added",
				" tail",
				marker + " conflicted.go",
				"index 3333333,4444444..5555555",
				"--- a/conflicted.go",
				"+++ b/conflicted.go",
				"@@@ -1,3 -1,3 +1,3 @@@",
				"  ctx",
				"- left",
				" -right",
				"++merged",
				"",
			}, "\n")

			_, hunks, files, err := ParseUnifiedDiffFormats(diff)
			if err != nil {
				t.Fatal(err)
			}
			if len(hunks) != 1 {
				t.Fatalf("hunks = %d, want 1 (combined hunk skipped)", len(hunks))
			}
			if hunks[0].FilePath != "normal.go" {
				t.Fatalf("hunk path = %q", hunks[0].FilePath)
			}
			if strings.Contains(hunks[0].Content, "@@@") || strings.Contains(hunks[0].Content, "merged") {
				t.Fatalf("combined-diff lines bled into previous hunk: %q", hunks[0].Content)
			}
			// The combined-diff section's header lines must not bleed into the
			// previous file's hunk either: the marker is a file boundary that
			// flushes it.
			for _, header := range []string{
				marker + " conflicted.go",
				"index 3333333,4444444..5555555",
				"--- a/conflicted.go",
				"+++ b/conflicted.go",
			} {
				if strings.Contains(hunks[0].Content, header) {
					t.Fatalf("combined-diff header %q bled into previous hunk: %q", header, hunks[0].Content)
				}
			}
			if want := " keep\n+added\n tail\n"; hunks[0].Content != want {
				t.Fatalf("previous hunk content = %q, want %q", hunks[0].Content, want)
			}
			if len(files) != 2 || files[0].Path != "normal.go" || files[1].Path != "conflicted.go" {
				t.Fatalf("files = %#v, want normal.go and conflicted.go", files)
			}
			if files[0].Additions != 1 || files[0].Deletions != 0 {
				t.Fatalf("normal.go additions/deletions = %d/%d, want 1/0", files[0].Additions, files[0].Deletions)
			}
			if files[1].Additions != 0 || files[1].Deletions != 0 {
				t.Fatalf("conflicted.go additions/deletions = %d/%d, want 0/0 (combined body skipped)", files[1].Additions, files[1].Deletions)
			}
		})
	}
}

// Hunk-body lines whose content itself starts with "++" or "--" (rendering as
// "+++..."/"---..." in the diff) are real added/deleted lines and must be
// counted; file headers can never appear inside a hunk body.
func TestParseUnifiedDiffFormatsCountsPlusPlusAndMinusMinusLines(t *testing.T) {
	diff := strings.Join([]string{
		"diff --git a/counter.c b/counter.c",
		"index 1111111..2222222 100644",
		"--- a/counter.c",
		"+++ b/counter.c",
		"@@ -1,3 +1,3 @@",
		" keep",
		"---counter;",
		"+++counter;",
		"",
	}, "\n")

	_, hunks, files, err := ParseUnifiedDiffFormats(diff)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 {
		t.Fatalf("files = %d, want 1", len(files))
	}
	if files[0].Additions != 1 || files[0].Deletions != 1 {
		t.Fatalf("additions/deletions = %d/%d, want 1/1 (++/-- content lines counted)", files[0].Additions, files[0].Deletions)
	}
	if len(hunks) != 1 || !strings.Contains(hunks[0].Content, "+++counter;") {
		t.Fatalf("hunk content missing ++ line: %#v", hunks)
	}
}

// "rename to" values are C-quoted by git for special/non-ASCII paths; the
// decoded path must win over the raw quoted string.
func TestParseUnifiedDiffFormatsUnquotesRenameTo(t *testing.T) {
	diff := strings.Join([]string{
		`diff --git "a/sch\303\266n old.txt" "b/sch\303\266n.txt"`,
		"similarity index 90%",
		`rename from "sch\303\266n old.txt"`,
		`rename to "sch\303\266n.txt"`,
		"",
	}, "\n")

	_, _, files, err := ParseUnifiedDiffFormats(diff)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 {
		t.Fatalf("files = %d, want 1", len(files))
	}
	if files[0].Path != "schön.txt" {
		t.Fatalf("renamed path = %q, want %q", files[0].Path, "schön.txt")
	}
	if files[0].Status != "renamed" {
		t.Fatalf("status = %q, want renamed", files[0].Status)
	}
}

// An unquoted "rename to" path passes through verbatim.
func TestParseUnifiedDiffFormatsPlainRenameTo(t *testing.T) {
	diff := strings.Join([]string{
		"diff --git a/old.txt b/new.txt",
		"similarity index 90%",
		"rename from old.txt",
		"rename to new.txt",
		"",
	}, "\n")

	_, _, files, err := ParseUnifiedDiffFormats(diff)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 || files[0].Path != "new.txt" {
		t.Fatalf("files = %#v, want new.txt", files)
	}
}

// The same protection applies when a combined hunk appears under a
// "diff --git" header: the file entry survives but no hunk is misparsed.
func TestParseUnifiedDiffFormatsSkipsCombinedHunkUnderGitHeader(t *testing.T) {
	diff := strings.Join([]string{
		"diff --git a/conflicted.go b/conflicted.go",
		"index 3333333,4444444..5555555",
		"@@@ -1,3 -1,3 +1,3 @@@",
		"  ctx",
		"++merged",
		"",
	}, "\n")

	_, hunks, files, err := ParseUnifiedDiffFormats(diff)
	if err != nil {
		t.Fatal(err)
	}
	if len(hunks) != 0 {
		t.Fatalf("hunks = %d, want 0", len(hunks))
	}
	if len(files) != 1 || files[0].Path != "conflicted.go" {
		t.Fatalf("files = %#v, want conflicted.go entry", files)
	}
	if files[0].Additions != 0 || files[0].Deletions != 0 {
		t.Fatalf("combined body lines were counted: %d/%d", files[0].Additions, files[0].Deletions)
	}
}
