package git

import (
	"strings"
	"testing"
)

func TestParseDiffGitPath(t *testing.T) {
	tests := []struct {
		name string
		line string
		want string
	}{
		{
			name: "plain",
			line: "diff --git a/main.go b/main.go",
			want: "main.go",
		},
		{
			name: "space in name unquoted",
			line: "diff --git a/dir/my file.go b/dir/my file.go",
			want: "dir/my file.go",
		},
		{
			name: "space in name quoted both sides",
			line: `diff --git "a/dir/my file.go" "b/dir/my file.go"`,
			want: "dir/my file.go",
		},
		{
			name: "umlaut octal escapes",
			line: `diff --git "a/sch\303\266n.txt" "b/sch\303\266n.txt"`,
			want: "schön.txt",
		},
		{
			name: "quotes in name both sides",
			line: `diff --git "a/say \"hi\".txt" "b/say \"hi\".txt"`,
			want: `say "hi".txt`,
		},
		{
			name: "doubled backslash",
			line: `diff --git "a/back\\slash.txt" "b/back\\slash.txt"`,
			want: `back\slash.txt`,
		},
		{
			name: "tab escape",
			line: `diff --git "a/ta\tb.txt" "b/ta\tb.txt"`,
			want: "ta\tb.txt",
		},
		{
			name: "mixed quoted a unquoted b",
			line: `diff --git "a/sch\303\266n.txt" b/plain.txt`,
			want: "plain.txt",
		},
		{
			name: "mixed unquoted a quoted b",
			line: `diff --git a/plain.txt "b/sch\303\266n.txt"`,
			want: "schön.txt",
		},
		{
			name: "unquoted rename",
			line: "diff --git a/old.go b/new.go",
			want: "new.go",
		},
		{
			name: "not a diff line",
			line: "index 1234567..89abcde 100644",
			want: "",
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := parseDiffGitPath(tc.line); got != tc.want {
				t.Fatalf("parseDiffGitPath(%q) = %q, want %q", tc.line, got, tc.want)
			}
		})
	}
}

func TestParseUnifiedDiffFormatsClassifiesWithContent(t *testing.T) {
	diff := strings.Join([]string{
		"diff --git a/bin/deploy b/bin/deploy",
		"new file mode 100755",
		"@@ -0,0 +1,2 @@",
		"+#!/usr/bin/env python",
		"+import sys",
		"diff --git a/api/service.pb.go b/api/service.pb.go",
		"@@ -1,2 +1,2 @@",
		"-// Code generated by protoc-gen-go. DO NOT EDIT.",
		"+// Code generated by protoc-gen-go v2. DO NOT EDIT.",
		"",
	}, "\n")

	diffFiles, hunks, _, err := ParseUnifiedDiffFormats(diff)
	if err != nil {
		t.Fatal(err)
	}
	if len(diffFiles) != 2 {
		t.Fatalf("diff files = %d, want 2", len(diffFiles))
	}
	if diffFiles[0].Language != "python" {
		t.Fatalf("bin/deploy language = %q, want python", diffFiles[0].Language)
	}
	if diffFiles[0].Generated {
		t.Fatal("bin/deploy marked generated")
	}
	if !diffFiles[1].Generated {
		t.Fatal("api/service.pb.go not marked generated")
	}
	if len(hunks) != 2 || hunks[0].Language != "python" {
		t.Fatalf("hunk language = %+v, want python for bin/deploy", hunks)
	}
}

// A combined-diff ("@@@") hunk from a merge state must not be swallowed as
// content of the preceding file's hunk; its lines are skipped instead.
func TestParseUnifiedDiffFormatsSkipsCombinedDiffHunks(t *testing.T) {
	// Combined diffs appear with either marker: "diff --cc" (git diff during a
	// merge) and "diff --combined" (git diff-tree -c and friends). Both must
	// act as a file boundary.
	for _, marker := range []string{"diff --cc", "diff --combined"} {
		t.Run(strings.TrimPrefix(marker, "diff --"), func(t *testing.T) {
			diff := strings.Join([]string{
				"diff --git a/normal.go b/normal.go",
				"index 1111111..2222222 100644",
				"--- a/normal.go",
				"+++ b/normal.go",
				"@@ -1,2 +1,3 @@",
				" keep",
				"+added",
				" tail",
				marker + " conflicted.go",
				"index 3333333,4444444..5555555",
				"--- a/conflicted.go",
				"+++ b/conflicted.go",
				"@@@ -1,3 -1,3 +1,3 @@@",
				"  ctx",
				"- left",
				" -right",
				"++merged",
				"",
			}, "\n")

			_, hunks, files, err := ParseUnifiedDiffFormats(diff)
			if err != nil {
				t.Fatal(err)
			}
			if len(hunks) != 1 {
				t.Fatalf("hunks = %d, want 1 (combined hunk skipped)", len(hunks))
			}
			if hunks[0].FilePath != "normal.go" {
				t.Fatalf("hunk path = %q", hunks[0].FilePath)
			}
			if strings.Contains(hunks[0].Content, "@@@") || strings.Contains(hunks[0].Content, "merged") {
				t.Fatalf("combined-diff lines bled into previous hunk: %q", hunks[0].Content)
			}
			// The combined-diff section's header lines must not bleed into the
			// previous file's hunk either: the marker is a file boundary that
			// flushes it.
			for _, header := range []string{
				marker + " conflicted.go",
				"index 3333333,4444444..5555555",
				"--- a/conflicted.go",
				"+++ b/conflicted.go",
			} {
				if strings.Contains(hunks[0].Content, header) {
					t.Fatalf("combined-diff header %q bled into previous hunk: %q", header, hunks[0].Content)
				}
			}
			if want := " keep\n+added\n tail\n"; hunks[0].Content != want {
				t.Fatalf("previous hunk content = %q, want %q", hunks[0].Content, want)
			}
			if len(files) != 2 || files[0].Path != "normal.go" || files[1].Path != "conflicted.go" {
				t.Fatalf("files = %#v, want normal.go and conflicted.go", files)
			}
			if files[0].Additions != 1 || files[0].Deletions != 0 {
				t.Fatalf("normal.go additions/deletions = %d/%d, want 1/0", files[0].Additions, files[0].Deletions)
			}
			if files[1].Additions != 0 || files[1].Deletions != 0 {
				t.Fatalf("conflicted.go additions/deletions = %d/%d, want 0/0 (combined body skipped)", files[1].Additions, files[1].Deletions)
			}
		})
	}
}

// A combined-diff section must still produce a DiffFile: its hunks cannot be
// represented two-way, so the raw patch text is the only representation left,
// and dropping it would hand a merge diff to an agent as "no changes".
func TestDiffFilesFromUnifiedDiffKeepsCombinedSections(t *testing.T) {
	for _, marker := range []string{"diff --cc", "diff --combined"} {
		t.Run(strings.TrimPrefix(marker, "diff --"), func(t *testing.T) {
			diff := strings.Join([]string{
				"diff --git a/normal.go b/normal.go",
				"index 1111111..2222222 100644",
				"--- a/normal.go",
				"+++ b/normal.go",
				"@@ -1,2 +1,3 @@",
				" keep",
				"+added",
				marker + " conflicted.go",
				"index 3333333,4444444..5555555",
				"--- a/conflicted.go",
				"+++ b/conflicted.go",
				"@@@ -1,3 -1,3 +1,3 @@@",
				"  ctx",
				"++merged",
				"",
			}, "\n")

			diffFiles := DiffFilesFromUnifiedDiff(diff)
			if len(diffFiles) != 2 {
				t.Fatalf("diff files = %#v, want normal.go and conflicted.go", diffFiles)
			}
			if diffFiles[1].FilePath != "conflicted.go" {
				t.Fatalf("combined diff file path = %q", diffFiles[1].FilePath)
			}
			if !strings.HasPrefix(diffFiles[1].Content, marker+" conflicted.go\n") {
				t.Fatalf("combined diff file content = %.80q", diffFiles[1].Content)
			}
			if !strings.Contains(diffFiles[1].Content, "++merged") {
				t.Fatalf("combined diff file content missing body: %.120q", diffFiles[1].Content)
			}
			if strings.Contains(diffFiles[0].Content, marker) {
				t.Fatalf("combined section bled into the previous diff file: %.120q", diffFiles[0].Content)
			}
		})
	}
}

// Hunk-body lines whose content itself starts with "++" or "--" (rendering as
// "+++..."/"---..." in the diff) are real added/deleted lines and must be
// counted; file headers can never appear inside a hunk body.
func TestParseUnifiedDiffFormatsCountsPlusPlusAndMinusMinusLines(t *testing.T) {
	diff := strings.Join([]string{
		"diff --git a/counter.c b/counter.c",
		"index 1111111..2222222 100644",
		"--- a/counter.c",
		"+++ b/counter.c",
		"@@ -1,3 +1,3 @@",
		" keep",
		"---counter;",
		"+++counter;",
		"",
	}, "\n")

	_, hunks, files, err := ParseUnifiedDiffFormats(diff)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 {
		t.Fatalf("files = %d, want 1", len(files))
	}
	if files[0].Additions != 1 || files[0].Deletions != 1 {
		t.Fatalf("additions/deletions = %d/%d, want 1/1 (++/-- content lines counted)", files[0].Additions, files[0].Deletions)
	}
	if len(hunks) != 1 || !strings.Contains(hunks[0].Content, "+++counter;") {
		t.Fatalf("hunk content missing ++ line: %#v", hunks)
	}
}

// "rename to" values are C-quoted by git for special/non-ASCII paths; the
// decoded path must win over the raw quoted string.
func TestParseUnifiedDiffFormatsUnquotesRenameTo(t *testing.T) {
	diff := strings.Join([]string{
		`diff --git "a/sch\303\266n old.txt" "b/sch\303\266n.txt"`,
		"similarity index 90%",
		`rename from "sch\303\266n old.txt"`,
		`rename to "sch\303\266n.txt"`,
		"",
	}, "\n")

	_, _, files, err := ParseUnifiedDiffFormats(diff)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 {
		t.Fatalf("files = %d, want 1", len(files))
	}
	if files[0].Path != "schön.txt" {
		t.Fatalf("renamed path = %q, want %q", files[0].Path, "schön.txt")
	}
	if files[0].Status != "renamed" {
		t.Fatalf("status = %q, want renamed", files[0].Status)
	}
}

// An unquoted "rename to" path passes through verbatim.
func TestParseUnifiedDiffFormatsPlainRenameTo(t *testing.T) {
	diff := strings.Join([]string{
		"diff --git a/old.txt b/new.txt",
		"similarity index 90%",
		"rename from old.txt",
		"rename to new.txt",
		"",
	}, "\n")

	_, _, files, err := ParseUnifiedDiffFormats(diff)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 || files[0].Path != "new.txt" {
		t.Fatalf("files = %#v, want new.txt", files)
	}
}

// The same protection applies when a combined hunk appears under a
// "diff --git" header: the file entry survives but no hunk is misparsed.
func TestParseUnifiedDiffFormatsSkipsCombinedHunkUnderGitHeader(t *testing.T) {
	diff := strings.Join([]string{
		"diff --git a/conflicted.go b/conflicted.go",
		"index 3333333,4444444..5555555",
		"@@@ -1,3 -1,3 +1,3 @@@",
		"  ctx",
		"++merged",
		"",
	}, "\n")

	_, hunks, files, err := ParseUnifiedDiffFormats(diff)
	if err != nil {
		t.Fatal(err)
	}
	if len(hunks) != 0 {
		t.Fatalf("hunks = %d, want 0", len(hunks))
	}
	if len(files) != 1 || files[0].Path != "conflicted.go" {
		t.Fatalf("files = %#v, want conflicted.go entry", files)
	}
	if files[0].Additions != 0 || files[0].Deletions != 0 {
		t.Fatalf("combined body lines were counted: %d/%d", files[0].Additions, files[0].Deletions)
	}
}

// A symlink blob's content is the link target path, not file text. Every git
// spelling of mode 120000 must mark the entry so reviewers do not judge the
// target as text — a "missing trailing newline" fix there rewrites the link.
func TestParseUnifiedDiffFormatsMarksSymlinkModes(t *testing.T) {
	tests := []struct {
		name string
		diff []string
		want bool
	}{
		{
			name: "added symlink",
			diff: []string{
				"diff --git a/link b/link",
				"new file mode 120000",
				"index 0000000..27fa349",
				"--- /dev/null",
				"+++ b/link",
				"@@ -0,0 +1 @@",
				"+other",
				"\\ No newline at end of file",
				"",
			},
			want: true,
		},
		{
			name: "changed symlink target",
			diff: []string{
				"diff --git a/link b/link",
				"index 1de5659..27fa349 120000",
				"--- a/link",
				"+++ b/link",
				"@@ -1 +1 @@",
				"-target",
				"\\ No newline at end of file",
				"+other",
				"\\ No newline at end of file",
				"",
			},
			want: true,
		},
		{
			name: "deleted symlink",
			diff: []string{
				"diff --git a/link b/link",
				"deleted file mode 120000",
				"index 1de5659..0000000",
				"--- a/link",
				"+++ /dev/null",
				"@@ -1 +0,0 @@",
				"-target",
				"\\ No newline at end of file",
				"",
			},
			want: true,
		},
		{
			name: "mode change into symlink",
			diff: []string{
				"diff --git a/link b/link",
				"old mode 100644",
				"new mode 120000",
				"",
			},
			want: true,
		},
		{
			// The post-change side is real text, so it must be reviewed as text.
			name: "symlink replaced by regular file",
			diff: []string{
				"diff --git a/link b/link",
				"old mode 120000",
				"new mode 100644",
				"",
			},
			want: false,
		},
		{
			name: "regular file",
			diff: []string{
				"diff --git a/main.go b/main.go",
				"index 1111111..2222222 100644",
				"--- a/main.go",
				"+++ b/main.go",
				"@@ -1 +1 @@",
				"-old",
				"+new",
				"",
			},
			want: false,
		},
		{
			// A hunk body line quoting a mode header must not be mistaken for one.
			name: "mode line inside hunk body",
			diff: []string{
				"diff --git a/notes.txt b/notes.txt",
				"index 1111111..2222222 100644",
				"--- a/notes.txt",
				"+++ b/notes.txt",
				"@@ -0,0 +1 @@",
				"+new file mode 120000",
				"",
			},
			want: false,
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			diffFiles, _, files, err := ParseUnifiedDiffFormats(strings.Join(tc.diff, "\n"))
			if err != nil {
				t.Fatal(err)
			}
			if len(files) != 1 {
				t.Fatalf("files = %#v, want one entry", files)
			}
			if files[0].Symlink != tc.want {
				t.Fatalf("ChangedFile.Symlink = %v, want %v", files[0].Symlink, tc.want)
			}
			if len(diffFiles) != 1 {
				t.Fatalf("diff files = %#v, want one entry", diffFiles)
			}
			if diffFiles[0].Symlink != tc.want {
				t.Fatalf("DiffFile.Symlink = %v, want %v", diffFiles[0].Symlink, tc.want)
			}
		})
	}
}

func TestSymlinkFromModes(t *testing.T) {
	tests := []struct {
		name    string
		oldMode string
		newMode string
		want    bool
	}{
		{name: "added symlink", oldMode: "0", newMode: "120000", want: true},
		{name: "deleted symlink", oldMode: "120000", newMode: "0", want: true},
		{name: "changed symlink", oldMode: "120000", newMode: "120000", want: true},
		{name: "symlink turned into file", oldMode: "120000", newMode: "100644", want: false},
		{name: "regular file", oldMode: "100644", newMode: "100644", want: false},
		{name: "missing modes", oldMode: "", newMode: "", want: false},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := SymlinkFromModes(tc.oldMode, tc.newMode); got != tc.want {
				t.Fatalf("SymlinkFromModes(%q, %q) = %v, want %v", tc.oldMode, tc.newMode, got, tc.want)
			}
		})
	}
}

// Replacing a tracked symlink with a regular file at the same path produces two
// sections: a mode-120000 deletion and a mode-100644 addition. Each entry must
// keep its own mark, or the regular file's real text gets treated as a link
// target and skipped in review.
func TestParseUnifiedDiffFormatsMarksReplacementEntriesIndependently(t *testing.T) {
	diff := strings.Join([]string{
		"diff --git a/link b/link",
		"deleted file mode 120000",
		"index 1de5659..0000000",
		"--- a/link",
		"+++ /dev/null",
		"@@ -1 +0,0 @@",
		"-target",
		"\\ No newline at end of file",
		"diff --git a/link b/link",
		"new file mode 100644",
		"index 0000000..c93cae4",
		"--- /dev/null",
		"+++ b/link",
		"@@ -0,0 +1 @@",
		"+real text",
		"",
	}, "\n")

	diffFiles, _, files, err := ParseUnifiedDiffFormats(diff)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 2 || len(diffFiles) != 2 {
		t.Fatalf("entries = %d changed / %d diff, want two of each", len(files), len(diffFiles))
	}
	if !files[0].Symlink || !diffFiles[0].Symlink {
		t.Fatalf("symlink deletion lost its mark: %#v / %#v", files[0], diffFiles[0])
	}
	if files[1].Symlink || diffFiles[1].Symlink {
		t.Fatalf("regular-file addition marked as symlink: %#v / %#v", files[1], diffFiles[1])
	}
}
