package workflows

import (
	"fmt"
	"strings"
)

// generatedExampleHeader marks workflow.yaml.example as generated, matching the
// banner config.ExampleYAML emits for .nickpit.yaml.example.
const generatedExampleHeader = "# Code generated by go generate ./workflows; DO NOT EDIT.\n\n"

// specMarker is the placeholder in example.tmpl replaced with the live default
// spec, so the example's executable steps always match the embedded default.
const specMarker = "{{SPEC}}"

// ExampleYAML renders workflow.yaml.example: the generated banner, the documented
// template, and the embedded default spec injected at the marker. cmd/nickpit-
// workflow-example writes the result; a golden test pins the checked-in file to it.
func ExampleYAML() ([]byte, error) {
	if !strings.Contains(exampleTemplate, specMarker) {
		return nil, fmt.Errorf("workflows: example template missing %s marker", specMarker)
	}
	body := strings.Replace(exampleTemplate, specMarker, string(defaultSpecYAML), 1)
	return []byte(generatedExampleHeader + body), nil
}
