apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nickpit-serve.fullname" . }}
  labels:
    {{- include "nickpit-serve.labels" . | nindent 4 }}
data:
  nickpit.yaml: |
    {{- .Values.config.nickpitYaml | nindent 4 }}
  server.yaml: |
    {{- include "nickpit-serve.serverYaml" . | nindent 4 }}
