package config

import (
	"bytes"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

const generatedExampleHeader = "# Code generated by go generate ./internal/config; DO NOT EDIT.\n\n"

func ExampleYAML() ([]byte, error) {
	cfg := DefaultConfig()
	root := yamlMapping(
		yamlEntry("active_profile", yamlScalar(cfg.ActiveProfile)),
		yamlEntry("profiles", exampleProfilesNode(cfg)),
	)
	doc := &yaml.Node{
		Kind:    yaml.DocumentNode,
		Content: []*yaml.Node{root},
	}

	var buf bytes.Buffer
	buf.WriteString(generatedExampleHeader)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, fmt.Errorf("config example: encoding yaml: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("config example: closing yaml encoder: %w", err)
	}
	return buf.Bytes(), nil
}

func exampleProfilesNode(cfg *Config) *yaml.Node {
	profiles := yamlMapping()
	for _, entry := range defaultProfiles {
		profile := cfg.Profiles[entry.name]
		profiles.Content = append(profiles.Content, yamlScalar(entry.name), exampleProfileNode(profile))
	}
	return profiles
}

func exampleProfileNode(profile Profile) *yaml.Node {
	profile = exampleProfile(profile)
	entries := []yamlNodeEntry{
		yamlEntry("model", yamlScalar(profile.Model)),
		yamlEntry("base_url", yamlScalar(profile.BaseURL)),
		yamlEntry("api_key", yamlScalar(profile.APIKey)),
		yamlEntry("max_context_tokens", yamlInt(profile.MaxContextTokens)),
		yamlEntry("max_tool_calls", yamlInt(profile.MaxToolCalls)),
		yamlEntry("max_duplicate_tool_calls", yamlInt(profile.MaxDuplicateToolCalls)),
		yamlEntry("github_token", yamlScalar(profile.GitHubToken)),
		yamlEntry("gitlab_token", yamlScalar(profile.GitLabToken)),
		yamlEntry("gitlab_base_url", yamlScalar(profile.GitLabBaseURL)),
	}
	return yamlMapping(entries...)
}

func exampleProfile(profile Profile) Profile {
	profile = cloneProfile(profile)
	profile.APIKey = canonicalEnvRef(profile.APIKey)
	if profile.MaxContextTokens == 0 && !profile.MaxContextTokensConfigured {
		profile.MaxContextTokens = DefaultMaxContextToken
	}
	if profile.MaxToolCalls == 0 && !profile.MaxToolCallsConfigured {
		profile.MaxToolCalls = MaxToolCalls
	}
	if profile.MaxDuplicateToolCalls == 0 && !profile.MaxDuplicateToolCallsConfigured {
		profile.MaxDuplicateToolCalls = DefaultMaxDuplicateToolCalls
	}
	if profile.GitHubToken == "" {
		profile.GitHubToken = DefaultGitHubTokenRef
	} else {
		profile.GitHubToken = canonicalEnvRef(profile.GitHubToken)
	}
	if profile.GitLabToken == "" {
		profile.GitLabToken = DefaultGitLabTokenRef
	} else {
		profile.GitLabToken = canonicalEnvRef(profile.GitLabToken)
	}
	if profile.GitLabBaseURL == "" {
		profile.GitLabBaseURL = DefaultGitLabBaseURLRef
	} else {
		profile.GitLabBaseURL = canonicalEnvRef(profile.GitLabBaseURL)
	}
	return profile
}

func canonicalEnvRef(value string) string {
	matches := envReferencePattern.FindStringSubmatch(strings.TrimSpace(value))
	if len(matches) == 0 {
		return value
	}
	name := matches[1]
	if name == "" {
		name = matches[2]
	}
	return "${" + name + "}"
}

type yamlNodeEntry struct {
	key   string
	value *yaml.Node
}

func yamlEntry(key string, value *yaml.Node) yamlNodeEntry {
	return yamlNodeEntry{key: key, value: value}
}

func yamlMapping(entries ...yamlNodeEntry) *yaml.Node {
	node := &yaml.Node{
		Kind: yaml.MappingNode,
		Tag:  "!!map",
	}
	for _, entry := range entries {
		node.Content = append(node.Content, yamlScalar(entry.key), entry.value)
	}
	return node
}

func yamlScalar(value string) *yaml.Node {
	return &yaml.Node{
		Kind:  yaml.ScalarNode,
		Tag:   "!!str",
		Value: value,
	}
}

func yamlInt(value int) *yaml.Node {
	return &yaml.Node{
		Kind:  yaml.ScalarNode,
		Tag:   "!!int",
		Value: fmt.Sprintf("%d", value),
	}
}
