package config

import (
	"bytes"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

const generatedExampleHeader = "# Code generated by go generate ./internal/config; DO NOT EDIT.\n\n"

func ExampleYAML() ([]byte, error) {
	cfg := DefaultConfig()
	root := yamlMapping(
		yamlEntry("active_profile", yamlScalar(cfg.ActiveProfile)),
		yamlEntry("profiles", exampleProfilesNode(cfg)),
	)
	doc := &yaml.Node{
		Kind:    yaml.DocumentNode,
		Content: []*yaml.Node{root},
	}

	var buf bytes.Buffer
	buf.WriteString(generatedExampleHeader)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, fmt.Errorf("config example: encoding yaml: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("config example: closing yaml encoder: %w", err)
	}
	return buf.Bytes(), nil
}

func exampleProfilesNode(cfg *Config) *yaml.Node {
	profiles := yamlMapping()
	for _, entry := range defaultProfiles {
		profile := cfg.Profiles[entry.name]
		profiles.Content = append(profiles.Content, yamlScalar(entry.name), exampleProfileNode(profile))
	}
	return profiles
}

func exampleProfileNode(profile Profile) *yaml.Node {
	profile = exampleProfile(profile)
	entries := []yamlNodeEntry{
		yamlEntry("model", yamlScalar(profile.Model)),
		yamlEntry("base_url", yamlScalar(profile.BaseURL)),
		yamlEntry("api_key", yamlScalar(profile.APIKey)),
		yamlEntry("supported_models", supportedModelsNode(profile.SupportedModels)),
		yamlEntry("include_paths", stringSliceNode(profile.IncludePaths)),
		yamlEntry("exclude_paths", stringSliceNode(profile.ExcludePaths)),
		yamlEntry("include_content", stringSliceNode(profile.IncludeContent)),
		yamlEntry("exclude_content", stringSliceNode(profile.ExcludeContent)),
		yamlEntry("max_context_tokens", yamlInt(profile.MaxContextTokens)),
		yamlEntry("max_tool_calls", yamlInt(profile.MaxToolCalls)),
		yamlEntry("max_duplicate_tool_calls", yamlInt(profile.MaxDuplicateToolCalls)),
		yamlEntry("max_output_retries", yamlInt(profile.MaxOutputRetries)),
		yamlEntry("max_reasoning_seconds", yamlInt(profile.MaxReasoningSeconds)),
		yamlEntry("max_reasoning_loop_repeats", yamlInt(profile.MaxReasoningLoopRepeats)),
		yamlEntry("max_rate_limit_delay_seconds", yamlInt(profile.MaxRateLimitDelaySeconds)),
		yamlEntry("nudge_count", yamlInt(profile.NudgeCount)),
		yamlEntry("disable_patch_summary", yamlBool(profile.DisablePatchSummary)),
		yamlEntry("reasoning_effort", yamlScalar(profile.ReasoningEffort)),
		yamlEntry("github_token", yamlScalar(profile.GitHubToken)),
		yamlEntry("gitlab_token", yamlScalar(profile.GitLabToken)),
		yamlEntry("gitlab_base_url", yamlScalar(profile.GitLabBaseURL)),
		yamlEntry("asset_base_url", yamlScalar(profile.AssetBaseURL)),
	}
	return yamlMapping(entries...)
}

func supportedModelsNode(models []ModelCapabilities) *yaml.Node {
	seq := &yaml.Node{Kind: yaml.SequenceNode}
	for _, model := range models {
		entries := []yamlNodeEntry{
			yamlEntry("model", yamlScalar(model.Model)),
			yamlEntry("compatible", yamlBool(model.Compatible)),
			yamlEntry("response", yamlBool(model.Response)),
			yamlEntry("tools", yamlBool(model.Tools)),
		}
		if model.JSONResponse != nil {
			entries = append(entries, yamlEntry("json_response", yamlBool(*model.JSONResponse)))
		}
		if model.JSONSchema != nil {
			entries = append(entries, yamlEntry("json_schema", yamlBool(*model.JSONSchema)))
		}
		entries = append(entries, yamlEntry("reasoning", yamlMapping(
			yamlEntry("traces", yamlBool(model.Reasoning.Traces)),
			yamlEntry("efforts", stringSliceNode(model.Reasoning.Efforts)),
		)))
		seq.Content = append(seq.Content, yamlMapping(entries...))
	}
	return seq
}

func stringSliceNode(values []string) *yaml.Node {
	seq := &yaml.Node{Kind: yaml.SequenceNode}
	for _, value := range values {
		seq.Content = append(seq.Content, yamlScalar(value))
	}
	return seq
}

func exampleProfile(profile Profile) Profile {
	profile = cloneProfile(profile)
	profile.APIKey = canonicalEnvRef(profile.APIKey)
	profile = applyProfileDefaults(profile)
	if profile.GitHubToken == "" {
		profile.GitHubToken = DefaultGitHubTokenRef
	} else {
		profile.GitHubToken = canonicalEnvRef(profile.GitHubToken)
	}
	if profile.GitLabToken == "" {
		profile.GitLabToken = DefaultGitLabTokenRef
	} else {
		profile.GitLabToken = canonicalEnvRef(profile.GitLabToken)
	}
	if profile.GitLabBaseURL == "" {
		profile.GitLabBaseURL = DefaultGitLabBaseURLRef
	} else {
		profile.GitLabBaseURL = canonicalEnvRef(profile.GitLabBaseURL)
	}
	return profile
}

func canonicalEnvRef(value string) string {
	matches := envReferencePattern.FindStringSubmatch(strings.TrimSpace(value))
	if len(matches) == 0 {
		return value
	}
	name := matches[1]
	if name == "" {
		name = matches[2]
	}
	return "${" + name + "}"
}

type yamlNodeEntry struct {
	key   string
	value *yaml.Node
}

func yamlEntry(key string, value *yaml.Node) yamlNodeEntry {
	return yamlNodeEntry{key: key, value: value}
}

func yamlMapping(entries ...yamlNodeEntry) *yaml.Node {
	node := &yaml.Node{
		Kind: yaml.MappingNode,
		Tag:  "!!map",
	}
	for _, entry := range entries {
		node.Content = append(node.Content, yamlScalar(entry.key), entry.value)
	}
	return node
}

func yamlScalar(value string) *yaml.Node {
	return &yaml.Node{
		Kind:  yaml.ScalarNode,
		Tag:   "!!str",
		Value: value,
	}
}

func yamlInt(value int) *yaml.Node {
	return &yaml.Node{
		Kind:  yaml.ScalarNode,
		Tag:   "!!int",
		Value: fmt.Sprintf("%d", value),
	}
}

func yamlBool(value bool) *yaml.Node {
	return &yaml.Node{
		Kind:  yaml.ScalarNode,
		Tag:   "!!bool",
		Value: fmt.Sprintf("%t", value),
	}
}
